<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Cities</h1>
        <div>a brand new Game</div>

            <p>
                Now playing cities in <b><?php echo $country; ?></b>
                <form onsubmit="sbm(); return false;">
                    <input id="city" type="text" name="city">
                </form>
            </p>

            <?php if (isset($words) && count($words)): ?>
                <?php foreach ($words as $word): ?>
                    <?php echo $word; ?><br/>
                <?php endforeach; ?>
            <?php endif; ?>
    </body>

    <script>
        document.getElementById('city').addEventListener('keypress', function(event) {
            if (event.keyCode == 13) {
                event.preventDefault();
                if (this.value) {
                    window.location = '/<?php echo $id; ?>/' + this.value;
                }
            }
        });
        function sbm(event) {
            event.preventDefault();
            return false;
        }
    </script>
</html>
